[build]
  publish = "."

# 表单提交成功后的重定向
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 表单处理设置
[build.processing.html]
  pretty_urls = true